/**
 * PM2 Ecosystem Configuration
 * Cluster Mode para aprovechar todos los cores del CPU
 * 
 * Uso:
 * - Desarrollo: pm2 start ecosystem.config.js --only gateway
 * - Producción: pm2 start ecosystem.config.js --env production
 * - Ver logs: pm2 logs
 * - Reiniciar: pm2 restart all
 * - Detener: pm2 stop all
 */

module.exports = {
  apps: [
    {
      name: 'gateway',
      script: './services/gateway/dist/services/gateway/src/main.js',
      instances: 'max', // Usa todos los cores disponibles
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/gateway-error.log',
      out_file: './logs/gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'eventos',
      script: './services/eventos/dist/services/eventos/src/main.js',
      instances: 2, // 2 instancias para balanceo
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3002,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3002,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/eventos-error.log',
      out_file: './logs/eventos-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'inscriptions',
      script: './services/inscriptions/dist/services/inscriptions/src/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3003,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3003,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/inscriptions-error.log',
      out_file: './logs/inscriptions-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teams',
      script: './services/teams/dist/services/teams/src/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3004,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3004,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/teams-error.log',
      out_file: './logs/teams-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'matches',
      script: './services/matches/dist/services/matches/src/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3005,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3005,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/matches-error.log',
      out_file: './logs/matches-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'referees',
      script: './services/referees/dist/services/referees/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/referees-error.log',
      out_file: './logs/referees-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'notifications',
      script: './services/notifications/dist/services/notifications/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/notifications-error.log',
      out_file: './logs/notifications-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'players',
      script: './services/players/dist/services/players/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_USER: 'wtt_user',
        DB_PASSWORD: 'N12lpWS1iTQ1#',
        DB_NAME: 'wtt_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      error_file: './logs/players-error.log',
      out_file: './logs/players-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
  ],
};
